### ISSUE TITLE
Localisation fails with Date Control and DatePicker 

### ISSUE THREAD

**Issue by deK1tErminAte** [kartik-v/yii2-datecontrol#65]
Hi Kartik,

i adore your work on all the enhancements of the framework, but i have an issue, maybe only a misconfiguration.

Everything went fine with your default configuration tips, based on the "en" locale and your documentation from the module. My Issue adresses the localisation of the DatePicker Widget, used in a view with a form field. The failure occurs when the php or ICU format contains a localized short or long month (like März for March). The $_POST for this field is empty and consequential nothing is stored in the Database. Potentially the localized months (like März or Februar) cant converted correctly by the DatePicker (*.js)? I dont have any expierience in Javascript-Debugging to go any further.

Have you any hints on my configuration or is this a **bug**?

I think this is likely the same issue from your [Comments & Discussion](https://disqus.com/home/discussion/krajee/invalid_configuration/#comment-1848335476).

The Localisation is switched with **public $language = 'de'** in the Application Configuraton.

I have also setup a **"vanilla" yii2 test-environment** (only yii2 app advanced, your widgets and the datecontrol module) to reproduce the issue.

Let me provide some of my configuration:

RDBMS: postgresql
target field: date (php:Y-m-d) checkout [postgres date](http://www.postgresql.org/docs/current/static/datatype-datetime.html)

main.php

```
'modules' => [
        'datecontrol' =>  [
            'ajaxConversion' => TRUE,
            'class' => '\kartik\datecontrol\Module',


             // format settings for displaying each date attribute (ICU format example)
            'displaySettings' => [
               Module::FORMAT_DATE => 'php:j. F Y',
               Module::FORMAT_TIME => 'HH:mm:ss a',
             Module::FORMAT_DATETIME => 'dd-MM-yyyy HH:mm:ss a', 
             ],
        
            // format settings for saving each date attribute (PHP format example)
            'saveSettings' => [
            Module::FORMAT_DATE => 'php:Y-m-d',
            Module::FORMAT_TIME => 'php:H:i:s',
            Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s',
            ],
 
            // set your display timezone
            'displayTimezone' => 'Europe/Berlin',
 
            // set your timezone for date saved to db
            'saveTimezone' => 'Europe/Berlin',
        
            // automatically use kartik\widgets for each of the above formats
            'autoWidget' => true,
 
            // default settings for each widget from kartik\widgets used when autoWidget is true
            'autoWidgetSettings' => [
                Module::FORMAT_DATE => ['type'=>2, 'pluginOptions'=>['autoclose'=>false]], // example
                Module::FORMAT_DATETIME => [], // setup if needed
                Module::FORMAT_TIME => [], // setup if needed
            ],
        
            // custom widget settings that will be used to render the date input instead of kartik\widgets,
            // this will be used when autoWidget is set to false at module or widget level.
            'widgetSettings' => [
                Module::FORMAT_DATE => [
                    'class' => 'yii\jui\DatePicker', // example
                    'options' => [
                        'dateFormat' => 'php:d-M-Y',
                        'options' => ['class'=>'form-control'],
                    ]
                ]
            ]
        ],

```

Application.php

snippet:

```
    /**
     * @var string the language that is meant to be used for end users. It is recommended that you
     * use [IETF language tags](http://en.wikipedia.org/wiki/IETF_language_tag). For example, `en` stands
     * for English, while `en-US` stands for English (United States).
     * @see sourceLanguage
     */
    public $language = 'de';
    /**
     * @var string the language that the application is written in. This mainly refers to
     * the language that the messages and view files are written in.
     * @see language
     */
    public $sourceLanguage = '';
```
Formatter Settings:

print_r(Yii::$app->formatter);

```
yii\i18n\Formatter Object ( [nullDisplay] => (not set) [booleanFormat] => Array ( [0] => No [1] => Yes ) [locale] => [timeZone] => UTC [defaultTimeZone] => UTC [dateFormat] => medium [timeFormat] => medium [datetimeFormat] => medium [decimalSeparator] => . [thousandSeparator] => , [numberFormatterOptions] => Array ( ) [numberFormatterTextOptions] => Array ( ) [numberFormatterSymbols] => Array ( ) [currencyCode] => [sizeFormatBase] => 1024 [_intlLoaded:yii\i18n\Formatter:private] => [_dateFormats:yii\i18n\Formatter:private] => Array ( [short] => 3 [medium] => 2 [long] => 1 [full] => 0 ) [_events:yii\base\Component:private] => Array ( ) [_behaviors:yii\base\Component:private] => ) 1
```

in the View (snippet):

```
    <?= $form->field($model, 'date_chair')->widget(DateControl::classname(), [
        'type'=>DateControl::FORMAT_DATE])?>
```

**Comment by kartik-v** [comment]
Related to #54.

**Comment by kartik-v** [comment]
Resolved via #66 without using `IntlDateFormatter` ... read why.

Currently this release is not tagged... you may get the dev-master code to test and then confirm.

**Comment by deK1tErminAte** [comment]
Thanks a lot!

**Comment by deK1tErminAte** [comment]
I updated the **"vanilla" yii2 test-environment** to the latest release, but unfortunately, this issue still exists. If a date is correctly set in database, the displayed date seems to be ok, but if a change the value with the DatePicker, the conversion still fails. A new entry fails respectively also.

**Comment by kartik-v** [comment]
- Check if you have updated code. Update again from the repo dev-master.
- Note that ISO / English format must be used for saving to database. 

You can check that the conversion works fine on the [demo page here](http://demos.krajee.com/datecontrol-demo). Try picking the language on the demo page and generate to see how different language date formats work.

**Comment by deK1tErminAte** [comment]
Yes, it is working now. At least, my composer setting for the DatePicker was hard-coded to 1.3.2. Sorry, i overlooked that. I will leave you a tip.
